Month 8/step 2
SergeyNerusin/react-burger pull request #4
Opened 2022-10-16 08:40 UTC by SergeyNerusin

2022-10-17 12:13 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Исправьте логику у модальных окон, уберите пропс `show`. Там должен быть только условный рендеринг. Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

  ```js
  {isOpen && (
      компонент открываемого попапа
  )}
  ```

- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер. Т.е компонент modal будет иметь такую структуру:

  ```js
  <>
    <div className={styles.modal}>{/** ... */}</div>
    <ModalOverlay onClick={onClose} />
  </>
  ```

- В компоненте Modal не правильно описаны propTypes для children (Проверьте во всём проекте). В документации есть пример, как можно сделать это правильно: https://ru.react.js.org/docs/typechecking-with-proptypes.html#%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D1%87%D0%B5%D1%80%D0%BD%D0%B5%D0%B3%D0%BE-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0

- Лучше не выносить отдельные dom элементы в константы (имею ввиду body в constant). body, следует перенести в компонент Modal, т.к элемент нигде больше не используется. Также следует перенести файл constants.js в папку utils.

- Имена констант принято записывать в стиле UPPER_CASE, исправьте apiUrl.

- Необходимо полное описание структуры, а не PropTypes.object.

- Поправьте логику рендера ингредиентов в burgerConstructor.

### **Сделает код лучше:**

- Оберните передаваемые данные в actionCreators в объект payload. Так мы сразу видим, какие данные передаются. Ну и это распространенная форма записи ActionCreators.

Например:

```js
export function addBurgerIngr(item) {
  return {
    type: ADD_BURGER_INGR,
    payload: {
      data: item,
      keyId: Date.now(),
    },
  };
}
```

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить".**

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/index.js
> +  burger: burgerConstructorReducer,
**Можно лучше:** лучше переименовать в burgerConstructor. Так будет более понятно, что здесь находиться.

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/actions/action-get-ingr.js
> +  .then(res => {
**Надо исправить:** Тут должен быть так же обработчик catch куда мы попадем в случае ошибки запроса (код ответа не 200). И там тоже нужно вызывать `dispatch({ type: GET_INGR_ERR });`

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/actions/action-get-ingr.js
> +export const GET_INGR_ERR = 'GET_INGR_ERR';
**Надо исправить:** Старайтесь писать в едином стиле. Тут нужно переименовать значение `GET_INGR_ERR` в `GET_INGR_ERROR`. И рекомендую писать полное название INGR - INGREDIENTS .

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/actions/action-constructor-ingr.js
> +    keyId: Date.now()
**Вы молодец:** Неплохое решение проблемы генерации уникального ключа.

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/actions/action-get-order.js
> +    fetchGetOrderNumber(ingredientsId)
**Надо исправить:** Похожую проблему описал в action-get-ingr.js

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/reducer-constructor-ingr.js
> +  ingredients: [],
**Надо исправить:** Если данных нет, то следует записывать null, а не пустой объект/массив.

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/actions/action-constructor-ingr.js
> +  };
**Надо исправить:** чтобы не было лишних действий в редьюсере, лучше написать вот так, так мы сразу внесём новый key в ингредиент. 

```js
return {
  type: ADD_BURGER_INGR, 
  data: { ...item, keyId: Date.now()  }, 
};
```

И еще, data лучше переименовать в `ingredient` или (что будет правильнее всего) в `payload`.
Тогда запись в редьюсере будет такой: 

```js
case ADD_BURGER_INGR: {
  return {
    ...state,
    ingredients: [...state.ingredients, action.payload];
  };
}
```

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/actions/action-constructor-ingr.js
> +}
**Можно лучше:** Можно реализовать данный функционал с помощью 1 actionCreator-а. В самом редьюсере допускаеться проверка на то, что объект имееть тип bun.

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/reducer-get-ing.js
> +  data: []
**Надо исправить:** Описал похожую проблему в reducer-constructor-ingr.js

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/reducer-get-order.js
> +       show: false
**Надо исправить:** а начальном стейте нету поля show, ну и плюс это излишний функционал (Подробнее написал в основном фидбеке).

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/reducer-show-inrg-details.js
> +  ingredient: {},
**Надо исправить:** Описал похожую проблему в reducer-constructor-ingr.js .

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/reducer-show-inrg-details.js
> +        active: true
**Надо исправить:** не оч понимаю зачем тут active, если можно следить напрямую за данными, `if(state.ingredient)`.

2022-10-17 12:13 UTC, ArslanMustafin commented on src/services/store/reducers/reducer-show-inrg-details.js
> +        ingredient: {},
**Надо исправить:** Здесь также следует передавать null.

2022-10-17 12:13 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      else {dispatch(addBurgerIngr(item))}
**Можно лучше:** Можно записать короче: 
```js
dispatch(item.type === 'bun' ? addBurgerBun(item) : dispatch(addBurgerIngr(item)))
```

2022-10-17 12:13 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  };
**Надо исправить:** данная функция избыточно, лучше делайте рендер сразу в jsx.

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-constructor/order-details/order-details.jsx
> +  const orderNumber = useSelector(store => store.order.order);
**Можно лучше:** Ради одного номера, не стоит использовать useSelector, лучше просто прокинуть пропс, это будет более оптимизированным вариантом.

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    let scrollDis = refContainer.current.scrollTop + 362;
**Надо исправить:** 

Если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          <Tab value='bun' active={current === 'bun'} onClick={() => handleMenuScroll('bun', bunRef)}>
**можно лучше:** Можно записать вот так: 
onClick - в данном случае, возвращает переданное значение value.
```js
onClick={(value) => handleMenuScroll(value, bunRef)}
```
тогда мы всегда будем зависеть от значения value.

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/section-ing/section-ing.jsx
> +  const {data} = useSelector(store => store.ingredients);
**Надо исправить:** Тут также лучше использовать для этого пропсы. Если мы будет использовать пропсы, то мы 1 раз получим ингредиенты в burgerIngredients, а также всего 1 раз сделаем фильтр. А тут это число умножаеться на 3. Вот оптимальная фильтрация ингредиентов: 

```js
  const buns = useMemo(
    () => ingredients.filter((item) => item.type === "bun"),
    [ingredients]
  );

  const mains = useMemo(
    () => ingredients.filter((item) => item.type === "main"),
    [ingredients]
  );

  const sauces = useMemo(
    () => ingredients.filter((item) => item.type === "sauce"),
    [ingredients]
  );
```

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/section-ing/section-ing.jsx
> +const SectionIng = ({typeIng, scrollToRef, ...props}) => {
**Надо исправить:** у вас остался только пропс children, не стоит указывать тут rest оператор, а то кажется, что у вас еще много пропсов осталось.

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient/ingredient.jsx
> +  const counter = setCounter();
**Можно лучше:** Почему бы сразу не вытащить из этой конструкции counter, используя useMemo.

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient/ingredient.jsx
>    data: PropTypes.object.isRequired,
**Надо исправить:** Необходимо полное описание структуры, а не PropTypes.object, так же необходимо указывать .isRequired как у элемента массива, так и у самого массива в проптайпс. Проверьте во всём проекте.

2022-10-17 12:13 UTC, ArslanDev666 commented on src/components/burger-constructor/order-details/order-details.jsx
> +      <h2 className="text text_type_digits-large mb-8" style={{fontSize: "40px", fontFamily: "Jet Brains Mono"}}>Запрос...</h2>}
**Надо исправить:** Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-10-20 04:00 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Критических ошибок в работе с Redux у вас нет.
- Почти все замечания с 1 ревью, были исправлены.

### **Но есть несколько новых замечаний, которые нужно исправить:**

- Вынести за пределы компонента переменную `body` в компоненте `Modal`.

- Правильно описать propTypes для children.

- Исправьте работу с PropTypes. в описании propTypes компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается. Проверьте во всем проекте.

  А также описание структуры должно выглядеть следующим образом:

  ```js
  export const ingredientPropType = PropTypes.shape({
    _id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.oneOf(["bun", "main", "sauce"]).isRequired,
    proteins: PropTypes.number.isRequired,
    fat: PropTypes.number.isRequired,
    carbohydrates: PropTypes.number.isRequired,
    calories: PropTypes.number.isRequired,
    price: PropTypes.number.isRequired,
    image: PropTypes.string.isRequired,
    image_large: PropTypes.string.isRequired,
    image_mobile: PropTypes.string.isRequired,
  });
  ```

  т.е везде следует указать `.isRequired`;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-10-20 04:00 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +  const body = document.querySelector('body');
**Надо исправить:** Лучше вынести за пределы компонента, иначе эта переменная будет создаваться каждый раз при рендере/ререндере.

2022-10-20 04:00 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +   }, []);
**Можно лучше:** Лучше передать в зависимости функцию onClose, т.к мы не всегда будем уверены, что ссылка на функцию будет актульной.

2022-10-20 04:00 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
>    children: PropTypes.object.isRequired,
**Надо исправить:** Не правильно описаны propTypes для children. В документации есть пример, как можно сделать это правильно: https://ru.react.js.org/docs/typechecking-with-proptypes.html#%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B4%D0%BE%D1%87%D0%B5%D1%80%D0%BD%D0%B5%D0%B3%D0%BE-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0

2022-10-20 04:00 UTC, ArslanMustafin commented on src/utils/burger-api.js
>  const checkResponse = (res) => {
**Можно лучше:** При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:

```js
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-10-20 04:00 UTC, ArslanMustafin commented on src/utils/burger-api.js
> +export const fetchGetOrderNumber = async(ingredientsId) => {
**Можно лучше:** Здесь и далее, если в функции не используется await, то не стоит указывать async.A

2022-10-20 04:00 UTC, ArslanMustafin commented on src/utils/constant.js
> +export default API_URL;
**Можно лучше:** лучше использовать такой экспорт, иначе вы не сможете добавить и экспортировать из файла новые константы. 

```js
import { API_URL } from './constant';
```

2022-10-20 04:00 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  const {ingredients} = useSelector(store => store.burgerConstructor);
**Можно лучше:** лучше обьединить в один `useSelector`: 

```js
const { bun, ingredients } = useSelector(store => store.burgerConstructor);
```

2022-10-20 04:00 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    scrollToRef.current.scrollIntoView();
**Можно лучше:** Реализуйте плавный скролл, для этого передайте такие параметры: 

```js
scrollToRef.current?.scrollIntoView({ behavior: "smooth" })
```

2022-10-20 04:00 UTC, ArslanMustafin commented on src/components/burger-ingredients/section-ing/section-ing.jsx
>    children: PropTypes.string.isRequired
**Надо исправить:** В описании `ingredietns` нужно указывать .isRequired, без этого не контролируется, что пропс передается.  Проверьте во всём проекте.

```js
  ingredietns: PropTypes.arrayOf(ingredientType.isRequired).isRequired,
```

а также, неправильно описаны пропсы для `children`. Ранее, в комментариях указывал ссылку на документацию с примером описания `children`.

2022-10-21 03:01 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы проделали отличную работу по рефакторингу!**

- Почти все замечания с прошлого ревью, были исправлены.

### **Но есть 1 небольшое замечание, которое нужно исправить:**

- Исправьте не большие недочёты в работе с PropTypes. Отметил проблемные места в коде.

## **Сделает код лучше:**

- не стоит так сильно сокращать слова: например, не нужно сокращать слово `ingredients` до `ingr`. Это не очень правильно с точки зрения `naming`. Вот неплохая статейка, хоть и старая: https://www.robinwieruch.de/javascript-naming-conventions/

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-10-21 03:01 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +   }, [onClose]);
**Можно лучше:** Сейчас, этот комментарий уже не актуален.

2022-10-21 03:01 UTC, ArslanMustafin commented on src/components/burger-ingredients/section-ing/section-ing.jsx
> +  listIngr: PropTypes.arrayOf(ingredientType).isRequired,
**Надо исправить:** 

Тут у вас всё было хорошо, также я в этом комментарии указал как правильно написать propTypes для `ingredients`. https://github.com/SergeyNerusin/react-burger/pull/4#discussion_r1000117139. 

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes. 

И верните старое название этому пропсу) оно было правильным, не стоит так сильно сокращать слово ingredients.

2022-10-21 03:01 UTC, ArslanMustafin commented on src/components/burger-constructor/item-consstructor/item-constructor.jsx
> +export default function ItemConstructor({ing, index, moveIngr}) {
**Надо исправить:** Для этого компонента, также следует описать PropTypes.

2022-10-21 03:01 UTC, ArslanMustafin commented on src/components/app/app.jsx
>  import Burgeringredients from '../burger-ingredients/burger-ingredients';
**Надо исправить:** Название компонентов, принято записывать в PascalCase. Просто исправьте тут название компонента на - `BurgerIngredients`

2022-10-21 03:16 UTC, SergeyNerusin commented on src/components/app/app.jsx
>  import Burgeringredients from '../burger-ingredients/burger-ingredients';
Доброе утро! Спасибо за замечания. Исправил.

2022-10-21 05:30 UTC, ArslanDev666 approved these changes
## Code Review

Доброе утро!

### **Отличная работа. Работа принята🔥!**

2022-11-07 16:19 UTC, merged